name: Lint PR

on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1   
      - name: Lint Code Base
        uses: docker://github/super-linter:v2.1.0
        env:
          VALIDATE_MD: false
